### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by knehez** [IONISx/edx-modulestore-node#4]
We have an edx install with a lot of courses. I tried out this app (with a lot of different connection strings), but we got an empty list:
```
node list-courses mongodb://edxapp:password@localhost/edxapp       
[]
```
What can be the problem?
Regards,
Charles

**Comment by tusbar** [comment]
Hello @knehez,

This module does not work with [Split Modulestore](http://edx-developer-guide.readthedocs.org/en/latest/modulestores/split-mongo.html), only with the old mongo modulestore.

That’s probably what’s happening here.

**Comment by knehez** [comment]
Ok I see, 
Thank you your reply!
